// This is an autogenerated file from Firebase Studio.

'use server';

/**
 * @fileOverview An AI agent that suggests healthier drink alternatives.
 *
 * - suggestHealthierDrink - A function that suggests healthier drink alternatives based on user input.
 * - SuggestHealthierDrinkInput - The input type for the suggestHealthierDrink function.
 * - SuggestHealthierDrinkOutput - The return type for the suggestHealthierDrink function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const SuggestHealthierDrinkInputSchema = z.object({
  favoriteDrink: z.string().describe('Your favorite drink.'),
  flavors: z.string().describe('Preferred flavors (e.g., sweet, fruity, sour).'),
  sugarContent: z
    .string()
    .describe('Preferred sugar content (e.g., low, medium, high).'),
});
export type SuggestHealthierDrinkInput = z.infer<
  typeof SuggestHealthierDrinkInputSchema
>;

const SuggestHealthierDrinkOutputSchema = z.object({
  suggestedDrink: z
    .string()
    .describe('A healthier alternative drink suggestion.'),
  recipeSuggestion: z
    .string()
    .optional()
    .nullable()
    .describe('A recipe suggestion from the recipe book, if available.'),
});
export type SuggestHealthierDrinkOutput = z.infer<
  typeof SuggestHealthierDrinkOutputSchema
>;

export async function suggestHealthierDrink(
  input: SuggestHealthierDrinkInput
): Promise<SuggestHealthierDrinkOutput> {
  return suggestHealthierDrinkFlow(input);
}

const recipeBookTool = ai.defineTool({
  name: 'getRecipeFromRecipeBook',
  description: 'Retrieves a drink recipe from the recipe book based on the specified criteria.',
  inputSchema: z.object({
    flavors: z
      .string()
      .describe('The flavors that the desired recipe should have.'),
    sugarContent: z
      .string()
      .describe('The sugar content that the desired recipe should have.'),
  }),
  outputSchema: z.string().optional().describe('A recipe from the recipe book.'),
  async fn(input) {
    // TODO: Implement the logic to retrieve a recipe from the recipe book.
    // This is a placeholder; replace it with actual data retrieval.
    console.log('Tool was called with', input);
    return undefined; /* Example:  `Ingredients: ... Instructions: ...` */
  },
});

const prompt = ai.definePrompt({
  name: 'suggestHealthierDrinkPrompt',
  input: {schema: SuggestHealthierDrinkInputSchema},
  output: {schema: SuggestHealthierDrinkOutputSchema},
  tools: [recipeBookTool],
  prompt: `You are a helpful AI assistant that suggests healthier alternatives to drinks.

  The user's favorite drink is: {{{favoriteDrink}}}
  They prefer flavors like: {{{flavors}}}
  They prefer a sugar content that is: {{{sugarContent}}}

  Suggest a healthier alternative drink that satisfies these preferences. 

  If the user's question asks about a recipe, include a recipe suggestion if available using the getRecipeFromRecipeBook tool.
  Do not force the use of tools, but guide the user towards them when appropriate.
  `,
});

const suggestHealthierDrinkFlow = ai.defineFlow(
  {
    name: 'suggestHealthierDrinkFlow',
    inputSchema: SuggestHealthierDrinkInputSchema,
    outputSchema: SuggestHealthierDrinkOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
