// This is an autogenerated file from Firebase Studio.

'use server';

/**
 * @fileOverview An AI agent that suggests healthier drink alternatives.
 *
 * - suggestHealthierDrink - A function that suggests healthier drink alternatives based on user input.
 * - SuggestHealthierDrinkInput - The input type for the suggestHealthierDrink function.
 * - SuggestHealthierDrinkOutput - The return type for the suggestHealthierDrink function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const SuggestHealthierDrinkInputSchema = z.object({
  favoriteDrink: z.string().describe('Your favorite drink.'),
  flavors: z.string().describe('Preferred flavors (e.g., sweet, fruity, sour).'),
  sugarContent: z
    .string()
    .describe('Preferred sugar content (e.g., low, medium, high).'),
});
export type SuggestHealthierDrinkInput = z.infer<
  typeof SuggestHealthierDrinkInputSchema
>;

const SuggestHealthierDrinkOutputSchema = z.object({
  suggestedDrink: z
    .string()
    .describe('A healthier alternative drink suggestion.'),
  recipeSuggestion: z
    .string()
    .optional()
    .nullable()
    .describe('A recipe suggestion from the recipe book, if available.'),
});
export type SuggestHealthierDrinkOutput = z.infer<
  typeof SuggestHealthierDrinkOutputSchema
>;

export async function suggestHealthierDrink(
  input: SuggestHealthierDrinkInput
): Promise<SuggestHealthierDrinkOutput> {
  return suggestHealthierDrinkFlow(input);
}

const recipeBookTool = ai.defineTool(
  {
    name: 'getRecipeFromRecipeBook',
    description: 'Retrieves a drink recipe from the recipe book based on the specified criteria.',
    inputSchema: z.object({
      flavors: z
        .string()
        .describe('The flavors that the desired recipe should have.'),
      sugarContent: z
        .string()
        .describe('The sugar content that the desired recipe should have.'),
    }),
    outputSchema: z.string().optional().describe('A recipe from the recipe book.'),
  },
  async (input: {flavors: string; sugarContent: string}) => {
    // TODO: Implement the logic to retrieve a recipe from the recipe book.
    // This is a placeholder; replace it with actual data retrieval.
    console.log('Tool was called with', input);
    if (input.flavors.toLowerCase().includes('fruity') && input.sugarContent === 'low') {
        return `Sparkling Berry Splash: \nIngredients: 1/2 cup mixed berries, 1 can of sparkling water, 1 tsp maple syrup (optional). \nInstructions: Muddle berries, top with sparkling water, and stir.`
    }
    return undefined; /* Example:  `Ingredients: ... Instructions: ...` */
  }
);

const prompt = ai.definePrompt({
  name: 'suggestHealthierDrinkPrompt',
  input: {schema: SuggestHealthierDrinkInputSchema},
  output: {schema: SuggestHealthierDrinkOutputSchema},
  tools: [recipeBookTool],
  prompt: `You are a wellness-focused barista AI. Your goal is to suggest a healthier and delicious alternative to the user's favorite drink.

  Follow these steps:
  1.  Analyze the user's preferences:
      -   Favorite Drink: {{{favoriteDrink}}}
      -   Preferred Flavors: {{{flavors}}}
      -   Preferred Sugar Content: {{{sugarContent}}}

  2.  Based on their preferences, come up with a single, specific, and appealing healthier drink suggestion. This is mandatory. Set this value in the 'suggestedDrink' output field.

  3.  Next, check if a relevant recipe is available using the 'getRecipeFromRecipeBook' tool based on the user's flavor and sugar preferences.
      -   If a recipe is found, place its full text in the 'recipeSuggestion' output field.
      -   If no recipe is found, leave the 'recipeSuggestion' field empty.

  Your response must be friendly and encouraging.
  `,
});

const suggestHealthierDrinkFlow = ai.defineFlow(
  {
    name: 'suggestHealthierDrinkFlow',
    inputSchema: SuggestHealthierDrinkInputSchema,
    outputSchema: SuggestHealthierDrinkOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
